### ISSUE TITLE
CUDA out of memory when using test data

### ISSUE THREAD

**Issue by 7rebor** [cabooster/DeepCAD#1]
Hi,

I really liked your paper on bioRxiv and wanted to compare results between DeepCAD and DeepInterpolation (Allen Institute). 

I managed to get model training to work on our analysis server with GPU, as per your instructions on Github. But, for some reason testing (e.g. `python script.py test`) runs out of GPU memory. 

Is there any way to change the batch size of testing so that I don't run out of GPU memory? I see that `batch_size=1` here, presumably the lowest already?

We have a RTX 2080 Ti GPU with 11 GB RAM, an additional 187 GB system RAM and an Intel(R) Xeon(R) Silver 4216 CPU @ 2.10GHz.

Many thanks,

Rob

```
the parameter of your training ----->                                                                                                     
Namespace(GPU=0, b1=0.5, b2=0.999, batch_size=1, cuda=False, datasets_folder='DataForPytorch', datasets_path='datasets', denoise_model='ModelForPytorch', epoch=0, gap_h=56, gap_s=400, gap_w=56, img_h=64, img_s=464, img_w=64, lr=0.001, n_epochs=100, normalize_factor=65535, output_dir='./results', pth_path='pth', test_datasize=6000, train_datasets_size=1000)
para.yaml                                                                                                                                 
{'GPU': 3, 'b1': 0.5, 'b2': 0.999, 'batch_size': 1, 'datasets_folder': '20201020_10_ZOOM1.3_550Vx575H_FOV_30Hz_170umdepth_soma_10AMP_0.3_0001', 'datasets_path': 'datasets', 'epoch': 0, 'gap_h': 64, 'gap_s': 150, 'gap_w': 64, 'img_h': 64, 'img_s': 464, 'img_w': 64, 'lr': 5e-05, 'n_epochs': 20, 'normalize_factor': 1, 'output_dir': './results', 'train_datasets_size': 1200}                                          
Using GPU.                                                                                                                                 
input_name ----->  DataForPytorch_x0_y0_z0                                                                                                
single_coordinate ----->  {'init_h': 0, 'end_h': 64, 'init_w': 0, 'end_w': 64, 'init_s': 0, 'end_s': 464, 'stack_start_w': 0, 'stack_end_w': 60.0, 'patch_start_w': 0, 'patch_end_w': 60.0, 'stack_start_h': 0, 'stack_end_h': 60.0, 'patch_start_h': 0, 'patch_end_h': 60.0, 'stack_start_s': 0, 'stack_end_s': 432.0, 'patch_start_s': 0, 'patch_end_s': 432.0}                                                            
real_A ----->  torch.Size([1, 1, 464, 64, 64])                                                                                             
[Batch 0/1215] [Time Left: 0:08:59.692619] [Time Cost: 0:00:00.444208] input_name ----->  DataForPytorch_x0_y0_z1
single_coordinate ----->  {'init_h': 0, 'end_h': 64, 'init_w': 0, 'end_w': 64, 'init_s': 400, 'end_s': 864, 'stack_start_w': 0, 'stack_end_w': 60.0, 'patch_start_w': 0, 'patch_end_w': 60.0, 'stack_start_h': 0, 'stack_end_h': 60.0, 'patch_start_h': 0, 'patch_end_h': 60.0, 'stack_start_s': 432.0, 'stack_end_s': 832.0, 'patch_start_s': 32.0, 'patch_end_s': 432.0}                                                   
real_A ----->  torch.Size([1, 1, 464, 64, 64])      
                                                                                      
Traceback (most recent call last):                                                                                                          
File "test.py", line 119, in <module>                                                                                                       
fake_B = denoise_generator(real_A)                                                                                                      
File "/home/rlees/anaconda3/envs/deepCAD/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl                   
result = self.forward(*input, **kwargs)                                                                                                 
File "/home/rlees/Documents/Code/DeepCAD/DeepCAD_pytorch/network.py", line 20, in forward     
fake_x = self.Generator(x)                                                                                                              
File "/home/rlees/anaconda3/envs/deepCAD/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl                   
result = self.forward(*input, **kwargs)                                                                                                 
File "/home/rlees/Documents/Code/DeepCAD/DeepCAD_pytorch/model_3DUnet.py", line 96, in forward                                            
x = decoder(encoder_features, x)                                                                                                        
File "/home/rlees/anaconda3/envs/deepCAD/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl                   
result = self.forward(*input, **kwargs)                                                                                                 
File "/home/rlees/Documents/Code/DeepCAD/DeepCAD_pytorch/buildingblocks.py", line 274, in forward                                           
x = F.interpolate(x, size=output_size, mode='nearest')                                                                                  
File "/home/rlees/anaconda3/envs/deepCAD/lib/python3.6/site-packages/torch/nn/functional.py", line 3134, in interpolate                     
return torch._C._nn.upsample_nearest3d(input, output_size, scale_factors)           
                                                  
RuntimeError: CUDA out of memory. Tried to allocate 928.00 MiB (GPU 0; 10.76 GiB total capacity; 9.23 GiB already allocated; 490.56 MiB free; 9.31 GiB reserved in total by PyTorch)
```

**Comment by 7rebor** [comment]
I think I have found my solution from this part of the methods section:

> The model was trained on 3D tiles with a spatial size of 64×64 pixels and a temporal size of 300 frames. Small spatial size can lower memory requirements and reduce the training time, and large temporal size is helpful to make full use of temporal information.

I am guessing I can reduce the temporal size a bit by adding that argument to the `script.py` file, e.g. `--img_s 200`. I will probably not change the spatial size as I presume it will start to under-perform with a smaller xy subset of pixels?

Could I ask for you to confirm that the `img_h`, `img_w` and `img_s` parameters are setting the size of the '3D tile' used for training and testing? Additionally, does the `gap_w`, `gap_h` and `gap_s` refer to the number of pixels/slices it will move to for the next 3D tile? 

What is `batch_size` setting?

Thanks!

**Comment by cabooster** [comment]
Because the network consumes a lot of Cuda memory, batchSize is set to 1. Because the network consumes a lot of video memory, batchSize is set to 1. Our training and testing were on a GPU with 24GB memory, so img_s is set to 464.

**Comment by cabooster** [comment]
> Hi,
> 
> I really liked your paper on bioRxiv and wanted to compare results between DeepCAD and DeepInterpolation (Allen Institute).
> 
> I managed to get model training to work on our analysis server with GPU, as per your instructions on Github. But, for some reason testing (e.g. `python script.py test`) runs out of GPU memory.
> 
> Is there any way to change the batch size of testing so that I don't run out of GPU memory? I see that `batch_size=1` here, presumably the lowest already?
> 
> We have a RTX 2080 Ti GPU with 11 GB RAM, an additional 187 GB system RAM and an Intel(R) Xeon(R) Silver 4216 CPU @ 2.10GHz.
> 
> Many thanks,
> 
> Rob
> 
> ```
> the parameter of your training ----->                                                                                                     
> Namespace(GPU=0, b1=0.5, b2=0.999, batch_size=1, cuda=False, datasets_folder='DataForPytorch', datasets_path='datasets', denoise_model='ModelForPytorch', epoch=0, gap_h=56, gap_s=400, gap_w=56, img_h=64, img_s=464, img_w=64, lr=0.001, n_epochs=100, normalize_factor=65535, output_dir='./results', pth_path='pth', test_datasize=6000, train_datasets_size=1000)
> para.yaml                                                                                                                                 
> {'GPU': 3, 'b1': 0.5, 'b2': 0.999, 'batch_size': 1, 'datasets_folder': '20201020_10_ZOOM1.3_550Vx575H_FOV_30Hz_170umdepth_soma_10AMP_0.3_0001', 'datasets_path': 'datasets', 'epoch': 0, 'gap_h': 64, 'gap_s': 150, 'gap_w': 64, 'img_h': 64, 'img_s': 464, 'img_w': 64, 'lr': 5e-05, 'n_epochs': 20, 'normalize_factor': 1, 'output_dir': './results', 'train_datasets_size': 1200}                                          
> Using GPU.                                                                                                                                 
> input_name ----->  DataForPytorch_x0_y0_z0                                                                                                
> single_coordinate ----->  {'init_h': 0, 'end_h': 64, 'init_w': 0, 'end_w': 64, 'init_s': 0, 'end_s': 464, 'stack_start_w': 0, 'stack_end_w': 60.0, 'patch_start_w': 0, 'patch_end_w': 60.0, 'stack_start_h': 0, 'stack_end_h': 60.0, 'patch_start_h': 0, 'patch_end_h': 60.0, 'stack_start_s': 0, 'stack_end_s': 432.0, 'patch_start_s': 0, 'patch_end_s': 432.0}                                                            
> real_A ----->  torch.Size([1, 1, 464, 64, 64])                                                                                             
> [Batch 0/1215] [Time Left: 0:08:59.692619] [Time Cost: 0:00:00.444208] input_name ----->  DataForPytorch_x0_y0_z1
> single_coordinate ----->  {'init_h': 0, 'end_h': 64, 'init_w': 0, 'end_w': 64, 'init_s': 400, 'end_s': 864, 'stack_start_w': 0, 'stack_end_w': 60.0, 'patch_start_w': 0, 'patch_end_w': 60.0, 'stack_start_h': 0, 'stack_end_h': 60.0, 'patch_start_h': 0, 'patch_end_h': 60.0, 'stack_start_s': 432.0, 'stack_end_s': 832.0, 'patch_start_s': 32.0, 'patch_end_s': 432.0}                                                   
> real_A ----->  torch.Size([1, 1, 464, 64, 64])      
>                                                                                       
> Traceback (most recent call last):                                                                                                          
> File "test.py", line 119, in <module>                                                                                                       
> fake_B = denoise_generator(real_A)                                                                                                      
> File "/home/rlees/anaconda3/envs/deepCAD/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl                   
> result = self.forward(*input, **kwargs)                                                                                                 
> File "/home/rlees/Documents/Code/DeepCAD/DeepCAD_pytorch/network.py", line 20, in forward     
> fake_x = self.Generator(x)                                                                                                              
> File "/home/rlees/anaconda3/envs/deepCAD/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl                   
> result = self.forward(*input, **kwargs)                                                                                                 
> File "/home/rlees/Documents/Code/DeepCAD/DeepCAD_pytorch/model_3DUnet.py", line 96, in forward                                            
> x = decoder(encoder_features, x)                                                                                                        
> File "/home/rlees/anaconda3/envs/deepCAD/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl                   
> result = self.forward(*input, **kwargs)                                                                                                 
> File "/home/rlees/Documents/Code/DeepCAD/DeepCAD_pytorch/buildingblocks.py", line 274, in forward                                           
> x = F.interpolate(x, size=output_size, mode='nearest')                                                                                  
> File "/home/rlees/anaconda3/envs/deepCAD/lib/python3.6/site-packages/torch/nn/functional.py", line 3134, in interpolate                     
> return torch._C._nn.upsample_nearest3d(input, output_size, scale_factors)           
>                                                   
> RuntimeError: CUDA out of memory. Tried to allocate 928.00 MiB (GPU 0; 10.76 GiB total capacity; 9.23 GiB already allocated; 490.56 MiB free; 9.31 GiB reserved in total by PyTorch)
> ```

Because the network consumes a lot of Cuda memory, batchSize is set to 1. Because the network consumes a lot of video memory, batchSize is set to 1. Our training and testing were on a GPU with 24GB memory, so img_s is set to 464.

**Comment by cabooster** [comment]
> Additionally, does the `gap_w`, `gap_h` and `gap_s` refer to the number of pixels/slices it will move to for the next 3D tile? Does the gap need to be smaller so the 3D tiles overlap in every dimension?

The meaning of gap is exactly what you say. If the gap is set too small, the test will take so much time, so we usually set it to 56(when img_w =img_h =64).
Because the network consumes a lot of Cuda memory, batchSize is set to 1. We will upgrade our algorithm to make it be able to speed up computation in parallel in the future. Our training and testing were on a GPU with 24GB memory, so img_s is set to 464.

**Comment by cabooster** [comment]
> I am guessing I can reduce the temporal size a bit by adding that argument to the `script.py` file, e.g. `--img_s 200`. I will probably not change the spatial size as I presume it will start to under-perform with a smaller xy subset of pixels?
>
> Could I ask for you to confirm that the `img_h`, `img_w` and `img_s` parameters are setting the size of the '3D tile' used for training and testing? Additionally, does the `gap_w`, `gap_h` and `gap_s` refer to the number of pixels/slices it will move to for the next 3D tile? Does the gap need to be smaller so the 3D tiles overlap in every dimension?
> 
> What is the `batch_size` setting for, is it the number of 3D tiles processed simultaneously?

The meanings of 'img', ’gap‘ and 'batch_size' are exactly what you say.  If the gap is set too small, the test process will take more time. So we usually set it to 56(when img_w =img_h =64).

According to our experience, larger spatial and temporal sizes can lead to better denoising performance, especially the temporal size.  

Because the 3D network consumes a lot of Cuda memory, batchSize is set to 1. We will upgrade our algorithm to enable parallel in the future. Our training and testing were on a GPU with 24GB memory, so img_s is set to 464.
