### ISSUE TITLE
The effect of different values of img_h,  img_w, img_s, gap_h, gap_w, gap_s when testing

### ISSUE THREAD

**Issue by z-pan** [cabooster/DeepCAD#11]
When testing the trained model, how do different values of img_h,  img_w, img_s, gap_h, gap_w, gap_s affect the output images?

**Comment by cabooster** [comment]
Larger img_h/img_s/img_w and smaller gap_h/gap_w/gap_s mean slightly better performance but longer inference time.

An upgraded version of the Pytorch code has been recently released at https://github.com/cabooster/DeepCAD-RT. In that version, we wrote detailed parameter comments and decrease the number of parameters.

In most cases, the following default parameter setting can work. You do not need to change it.
![image](https://user-images.githubusercontent.com/71710781/230759558-14096ac8-d876-4b50-a5ae-16304e3bfec0.png)

This new version has several new features such as much faster processing speed, low memory cost, improved pre- and post-processing, multi-GPU acceleration, more stable performance, etc. You can try it for better convenience. I hope it can help you.
