### ISSUE TITLE
Testing multiple models

### ISSUE THREAD

**Issue by 7rebor** [cabooster/DeepCAD#3]
1. Can the test.py argument `'--denoise_model'` be a directory containing multiple models? This is implied by the tip: `'A folder containing models to be tested'`, but I wanted to check with you. If not, I guess I could run the `test.py` programmatically in a loop for each model with different arguments?
2. Will it create an output for each model during testing in the `--output_dir`, if the above answer is yes?

**Comment by cabooster** [comment]
Yes, it will create an output for each model.
