### ISSUE TITLE
Tiled output appearance

### ISSUE THREAD

**Issue by 7rebor** [cabooster/DeepCAD#4]
Hi cabooster,

The output .tif files appear tiled, and this makes sense as the data is split in to tiles to denoise and then reconstructed again. Is it intended to appear tiled? Do you have any tips to rectify this? 

In the case below I used your model, and the recommended 64x64 tile size with 56x56 gaps. The first few frames are very obvious, but it soon corrects to a point where it is not obvious, but it is still concerning as cells can be on the border of a tile - this messes with ROI detection and relative intensity from tile to tile.

![image](https://user-images.githubusercontent.com/34678833/108202296-ce589e00-7118-11eb-9129-b4dfb57dc5d0.png)

**Comment by cabooster** [comment]
Hi Robert,
I have sent you an email to help you solve this problem.
