### ISSUE TITLE
fiji error resahpe tensor

### ISSUE THREAD

**Issue by alcrevenna** [cabooster/DeepCAD#5]
Dear authors, this seems to be a great tool. One that for sure many people will use. I was curious to try it out, and got the fiji plugin, but when trying to run it I get the following error - see below.

Any chance of help?

best, 
Alvaro

Info: 1024 frames stack of 256x256px, using 8, 8 of x,y overlap and 32, 64 or 128 or z overlap.
Running on linux ubuntu

 [ERROR] Module threw exception
java.lang.IllegalArgumentException: Input to reshape is a tensor with 2147483648 values, but the requested shape has 41943040
	 [[{{node group_normgn_enc_conv0/Reshape}}]]
	at org.tensorflow.Session.run(Native Method)
	at org.tensorflow.Session.access$100(Session.java:48)
	at org.tensorflow.Session$Runner.runHelper(Session.java:326)
	at org.tensorflow.Session$Runner.run(Session.java:276)
	at network.ModelExecutor.N2NDenoising(ModelExecutor.java:82)
	at network.ModelExecutor.run(ModelExecutor.java:351)
	at commands.DetectTiledImage.run(DetectTiledImage.java:183)
	at org.scijava.command.CommandModule.run(CommandModule.java:196)
	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:165)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:124)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:63)
	at org.scijava.thread.DefaultThreadService.lambda$wrap$2(DefaultThreadService.java:225)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by cabooster** [comment]
Hi, Alvaro, did you try the plugin with our example data? If the example data works, I think the problem may on your data format, especially the channel arrangement of your data. Also, our plugin was developed on windows, this could be the  a reason but with very small probability.

**Comment by alcrevenna** [comment]
Hi, thanks for the fast reply. I did try to example data and that worked fine. I am sure I am doing something wrong, I just don't know what. For the example data I left the parameters as default (64, 64, 320, 8, 8 128), although the pixel size of the image is 256. If I crop my movie to 256, 256 px by 320 and I use those default parameters it runs ok. But when I try only to increase the number of frames (say to 1024) then I get an error. Why the pixel size should be 64 and not 256? And why does it give me an error only when I change the number of frames? Any help is appreciated. Alvaro

**Comment by cabooster** [comment]
Thanks for your feedback. We will test the plugin following your condition, and then fix the bug after we find it.

**Comment by cabooster** [comment]
Hi Alvaro, I tried 256x256x1024 input stacks but no error occurred. I think your data format may not match ours. The default parameters (64, 64, 320, 8, 8 128) mean the patch size, not the input stack size.

**Comment by alcrevenna** [comment]
Hi, I discovered the error, which was I was assuming the 64,64,320 refered to the stack size. I was changing 320 to 1000 and that was making the program crash. So, its running now. Question, I am running a 5000 frame movie (256x256 px) and has been running for a couple of hours at least, is that normal? Would it be faster if I run things from python? Do you have a spike inference pipeline ;-)? In any case, thank you, the plugin is great and the results are fantastic. Now we want to process all of our movies using this tool (which is why we want to make things faster). best, Alvaro

**Comment by cabooster** [comment]
Hi Alvaro, I‘m very glad that our plugin can help you! For the low processing speed, I think you just used a CPU for processing. If you have a powerful GPU on your device, You can try GPU acceleration following the `GPU support` in [this page](https://github.com/CSBDeep/CSBDeep_website/wiki/CSBDeep-in-Fiji-%E2%80%93-Installation). The python code was developed with GPU and the processing speed was fast. For spike inference, we used the [MLspike](https://www.nature.com/articles/ncomms12190) toolbox. Their code has been released in https://github.com/MLspike/spikes and I think you can try it.
