### ISSUE TITLE
Help installing FIJI plugin 

### ISSUE THREAD

**Issue by diegoasua** [cabooster/DeepCAD#7]
Hi,

I am following the [instructions](https://github.com/cabooster/DeepCAD/tree/master/DeepCAD_Fiji) to setup the FIJI plugin but I can't get it installed. After downloading and installing, FIJI asks to reboot the application for changes to take effect. I did so, but then DeepCAD does not appear among the installed plugins or in the search bar. I made a fresh FIJI installation but the problem persisted, and same problem observed with both `DeepCAD-0.3.0.jar` and `DeepCAD-0.3.6.jar` I am running on Linux:

```bash
LSB Version:	:core-4.1-amd64:core-4.1-noarch
Distributor ID:	RedHatEnterpriseServer
Description:	Red Hat Enterprise Linux Server release 7.9 (Maipo)
Release:	7.9
Codename:	Maipo
Fiji:		2.1.0
Java:		1.8.0
```

**Comment by cabooster** [comment]
Thanks for your feedback. The plugin was developed and tested on Windows. Could you please try it on a windows system? We will test it on Linux as soon as possible.
