### ISSUE TITLE
Expected processing time, sample data

### ISSUE THREAD

**Issue by Sverreg** [cabooster/DeepCAD#8]
I'm having some issues getting DeepCAD to run on the GPU, I think. It would help to know how long you estimate it will take to run the tutorial data?

On my Ubuntu 20.04 system with an rtx2080Ti, it seems to take about 22 minutes to process one of the tutorial data files. Is this what you would expect? 

With the supplied model and default settings.

**Comment by cabooster** [comment]
Hi Sverreg. Do you mean the python code? And please specify the data size. If you want to check whether Fiji is using GPU, you can check the status of your GPU.

**Comment by Sverreg** [comment]
Oops, sorry I should have specified. I'm running it in Fiji using the tutorial on [this page.](https://github.com/cabooster/DeepCAD/tree/master/DeepCAD_Fiji) It doesn't appear to be using the GPU, at least not a lot of it.. I expect it's a problem with CUDA/Tensorflow. I tried to e-mail the contact us link on [this page,](https://github.com/CSBDeep/CSBDeep_website/wiki/CSBDeep-in-Fiji-%E2%80%93-Installation) but the address didn't work.

**Comment by cabooster** [comment]
I think you are using only CPU. CSBDeep seems to have bad GPU support. We also used CPU and the processing time is very close to yours. For the python code with GPU support, the example data can be processed within several seconds.

**Comment by Sverreg** [comment]
Thanks for the fast reply, I'll have a go with Python. Very happy to hear that it can be processed in seconds!
